import { ArrowLeft, Eye, EyeOff, KeyRound, LockKeyhole, Mail, MessageCircle, RefreshCw, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import useAuth from '../hooks/useAuth.js';
import './LoginPage.css';
function ForgotPasswordPage() {
  const { isSubmitting, requestPasswordReset, resendPasswordResetOtp, resetPassword, verifyPasswordResetOtp } = useAuth(); const navigate = useNavigate(); const [email,setEmail]=useState(''); const [otp,setOtp]=useState(''); const [password,setPassword]=useState(''); const [confirmPassword,setConfirmPassword]=useState(''); const [resetToken,setResetToken]=useState(''); const [step,setStep]=useState('email'); const [notice,setNotice]=useState(''); const [error,setError]=useState(''); const [showPassword,setShowPassword]=useState(false);
  async function requestCode(e){e.preventDefault();setError('');try{const r=await requestPasswordReset(email);setNotice(r.message);setStep('otp');}catch(x){setError(x.response?.data?.message||'Unable to send a reset code.');}}
  async function verifyCode(e){e.preventDefault();setError('');try{const r=await verifyPasswordResetOtp({email,otp});setResetToken(r.resetToken);setNotice(r.message);setStep('password');}catch(x){setError(x.response?.data?.message||'Unable to verify the code.');}}
  async function savePassword(e){e.preventDefault();setError('');if(password!==confirmPassword){setError('Passwords do not match.');return;}try{const r=await resetPassword({email,resetToken,newPassword:password});navigate('/login',{replace:true,state:{notice:r.message}});}catch(x){setError(x.response?.data?.message||'Unable to update your password.');}}
  async function resendCode(){setError('');try{const r=await resendPasswordResetOtp(email);setNotice(r.message);setOtp('');}catch(x){setError(x.response?.data?.message||'Unable to resend the code.');}}
  return <main className="login-page"><section className="login-card"><button type="button" className="login-back" onClick={()=>navigate('/login')}><ArrowLeft size={17}/> Back to login</button><div className="login-brand"><span><MessageCircle size={22}/></span> Chatly<b>AI</b></div><p className="login-kicker">Account recovery</p><h1>{step==='email'?'Forgot password?':step==='otp'?'Verify reset code':'Set a new password'}</h1><p className="login-intro">{step==='email'?'Enter your email and we will send a secure reset code.':step==='otp'?`Enter the code sent to ${email}.`:'Choose a strong password you have not used before.'}</p>{notice&&<p className="verify-email-notice">{notice}</p>}{error&&<p className="login-error">{error}</p>}{step==='email'?<form className="login-form" onSubmit={requestCode}><label><span>Email address</span><div className="login-input"><Mail size={18}/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" placeholder="you@example.com"/></div></label><button className="login-submit" disabled={isSubmitting}>Send reset code</button></form>:step==='otp'?<form className="login-form" onSubmit={verifyCode}><label><span>6-digit reset code</span><div className="login-input"><KeyRound size={18}/><input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" required placeholder="000000"/></div></label><button className="login-submit" disabled={isSubmitting||otp.length!==6}><ShieldCheck size={18}/> Verify code</button><button className="login-back" type="button" onClick={resendCode} disabled={isSubmitting}><RefreshCw size={15}/> Resend code</button></form>:<form className="login-form" onSubmit={savePassword}><label><span>New password</span><div className="login-input"><LockKeyhole size={18}/><input type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} minLength="8" required/><button type="button" onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><label><span>Confirm new password</span><div className="login-input"><LockKeyhole size={18}/><input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength="8" required/></div></label><button className="login-submit" disabled={isSubmitting}>Set new password</button></form>}<p className="login-switch">Remembered your password? <Link to="/login">Log in</Link></p></section></main>;
}
export default ForgotPasswordPage;